apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: nginx-app-rules
spec:
  groups:
    - name: nginx
      rules:
        - alert: HighCPUUsage
          expr: (sum(rate(container_cpu_usage_seconds_total{container_name!="POD"}[2m])) / sum(machine_cpu_cores)) * 100 > 5
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: High CPU Usage
            description: CPU usage is above 50%
        - alert: HighMemoryUsage
          expr: (sum(container_memory_usage_bytes{container_name!="POD"}) / sum(machine_memory_bytes)) * 100 > 5
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: High Memory Usage
            description: Memory usage is above 50%