apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    job: nginx
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: nginx-port
      port: 5050
      targetPort: 5050
      protocol: TCP
