apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-pod-monitor
  release: prometheus
  app: prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  podMetricsEndpoints:
    - port: nginx-port
      interval: 30s