apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-pod-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  podMetricsEndpoints:
    - port: nginx-pod-port
      interval: 30s
      path: /metrics