apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: web
      interval: 30s
      path: /swagger-stats/metrics