grafana:
  adminPassword: highly-secure-production-password

alertmanager:
  config:
    route:
      receiver: "null"
      routes:
      - match:
          severity: critical
        receiver: google-chat
        group_by: [alertname]
    receivers:
    - name: "null"
    - name: 'google-chat'
      webhook_configs:
      - url: "http://127.0.0.1:6000/create?room_name=app.chat.monitoring"