# Default values for calert.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configmap:
    # All timeouts and durations are in milliseconds.
  server:
    address: ":6000"
    socket: "/tmp/calert.sock"
    name: "calert"
    # WARNING If these timeouts are less than 1s, the server connection breaks.
    read_timeout: "8000"
    write_timeout: "8000"
    keepalive_timeout: "300000"
  app:
    template_file: "message.tmpl"
    http_client:
      max_idle_conns: "50"
      request_timeout: "30s"
  rooms: |
    [app.chat.monitoring]
    notification_url = "https://chat.googleapis.com/v1/spaces/AAAAjRsVsBA/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=oRFGJbwimDsjQ3XCIwFmHDrZIqFIEWnhtwlERXajY2E"

template_file: |
  *{{ .Labels.alertname | Title }} - {{.Status | Title }} ({{.Labels.severity | toUpper }})*
  {{ range .Annotations.SortedPairs -}}
  {{ .Name }}: {{ .Value}}
  {{ end -}}

replicaCount: 1

image:
  repository: mrkaran/calert
  tag: 1.0.0-stable
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 30010

ingress:
  enabled: false

resources:
  limits:
    cpu: 20m
    memory: 48Mi
  requests:
    cpu: 5m
    memory: 24Mi

nodeSelector: {}

tolerations: []

affinity: {}
